import css from "@/constants/style";
import { Text, View } from "react-native";

export default function UserGuide() {
  return (
    <View>
      <Text style={css.heading}>User Guide</Text>

      <Text style={css.text}>
        This application allows users to view trends from various open APIs :
      </Text>

      <Text style={css.text}>
        - Operations data is generated by the app for demo purposes
      </Text>

      <Text style={css.text}>- Rainfall data is sourced from the SEPA API</Text>

      <Text style={css.text}>
        - Carbon data is sourced from the National Grid API
      </Text>
    </View>
  );
}
